(() => {
  'use strict';
  const CONFIG = Object.freeze({timeZone:'Australia/Melbourne',debug:new URLSearchParams(location.search).get('debug')==='1',videoSources:Object.freeze({hour:'assets/videos/hour-placeholder.mp4',minute:'assets/videos/minute-placeholder.mp4',second:'assets/videos/second-placeholder.mp4'})});
  const videos={hour:document.querySelector('#hour-video'),minute:document.querySelector('#minute-video'),second:document.querySelector('#second-video')};
  const values={hour:document.querySelector('#hour-value'),minute:document.querySelector('#minute-value'),second:document.querySelector('#second-value')};
  const dateNodes=[...document.querySelectorAll('.panel-date')];const miniClocks=[...document.querySelectorAll('.mini-clock')];const debugNode=document.querySelector('#debug');let lastSecond='';let timer=0;
  function partsNow(){const formatter=new Intl.DateTimeFormat('en-AU',{timeZone:CONFIG.timeZone,weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});const parts=formatter.formatToParts(new Date());const map=Object.fromEntries(parts.map(({type,value})=>[type,value]));return{day:`${map.weekday} ${map.day} ${map.month}`.toUpperCase(),hour:map.hour.padStart(2,'0'),minute:map.minute.padStart(2,'0'),second:map.second.padStart(2,'0')}}
  function renderClock(){const now=partsNow();if(now.second===lastSecond)return;lastSecond=now.second;values.hour.textContent=now.hour;values.minute.textContent=now.minute;values.second.textContent=now.second;dateNodes.forEach(node=>{node.textContent=now.day});const full=`${now.hour}:${now.minute}:${now.second}`;miniClocks.forEach(node=>{node.textContent=full;node.dateTime=full});renderDebug(now)}
  function videoState(video){return`${video.readyState}/${video.networkState} ${video.paused?'paused':'playing'} ${Number.isFinite(video.currentTime)?video.currentTime.toFixed(2):'0.00'}s`}
  function renderDebug(now=partsNow()){if(!CONFIG.debug)return;const rect=document.querySelector('#stage').getBoundingClientRect();debugNode.hidden=false;debugNode.textContent=[`native 3840×804 | viewport ${innerWidth}×${innerHeight}`,`stage ${Math.round(rect.width)}×${Math.round(rect.height)} | scale ${(rect.width/3840).toFixed(4)}`,`Melbourne ${now.day} ${now.hour}:${now.minute}:${now.second}`,`hour   ${videoState(videos.hour)}`,`minute ${videoState(videos.minute)}`,`second ${videoState(videos.second)}`,`fonts ${document.fonts.status}`].join('\n')}
  async function ensurePlaying(video){try{await video.play()}catch(_){}}
  function initVideo(kind,video){video.src=CONFIG.videoSources[kind];video.addEventListener('loadeddata',()=>ensurePlaying(video),{passive:true});video.addEventListener('error',()=>renderDebug(),{passive:true});video.load();ensurePlaying(video)}
  function retryPlayback(){Object.values(videos).forEach(video=>{if(video.paused&&video.readyState>=2)ensurePlaying(video)})}
  function scheduleTick(){clearTimeout(timer);const delay=1000-(Date.now()%1000)+8;timer=setTimeout(()=>{renderClock();retryPlayback();scheduleTick()},delay)}
  Object.entries(videos).forEach(([kind,video])=>initVideo(kind,video));renderClock();scheduleTick();document.addEventListener('visibilitychange',()=>{if(!document.hidden)retryPlayback()},{passive:true});window.addEventListener('resize',()=>renderDebug(),{passive:true});window.addEventListener('pointerdown',retryPlayback,{once:true,passive:true});
})();
